builders:
  asset_builder:
    import: "package:lazy_asset_generator/lazy_asset_generator.dart"
    builder_factories: ["assetFolderBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
